name: videogamesordie
favicon: null
layout_spectrum: 0.354611421469599
typography_spectrum: 0.2518
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c44741'
    - '#000000'
    - '#c4c4c4'
    - '#494949'
  brandStrength: 0.54109449358657
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
