name: videogamesordie
favicon: null
layout_spectrum: 0.354611421469599
typography_spectrum: 0.485997466603294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.54109449358657
  lightness: 0.020996520528569818
  saturation: 0.7084365000482649
  rhythmicContrast: 0.0898799488786608
purpose: []
